version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-ctn1
    ports:
      - 7080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html/:/var/www/html
    restart: always